version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 652698421662.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - docker build -t myapp .
      - docker tag myapp:latest 652698421662.dkr.ecr.ap-south-1.amazonaws.com/my-repo

  post_build:
    commands:
      - docker push 652698421662.dkr.ecr.ap-south-1.amazonaws.com/my-repo
